version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: realestate-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realestate_db
      TZ: Europe/Paris
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s  # temps dâ€™attente avant premier test

  backend:
    build:
      context: ./realestate-backend
      dockerfile: Dockerfile
    container_name: realestate-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/realestate_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    depends_on:
      mysql:
        condition: service_healthy


  frontend:
    build:
      context: ./realestate-frontend
      dockerfile: Dockerfile
    container_name: realestate-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./realestate-frontend:/app

volumes:
  mysql_data:
